# Generated by Django 4.2 on 2023-04-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ttt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="atadmin",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Received"),
                    (1, "Processing"),
                    (2, "Shipped"),
                    (3, "Closed"),
                ],
                default=0,
            ),
        ),
    ]
