# Generated by Django 4.2 on 2023-04-07 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ttt", "0003_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "lob",
                    models.CharField(
                        choices=[
                            ("CNS", "CNS"),
                            ("EIS", "EIS"),
                            ("EWP", "EWP"),
                            ("PS", "PS"),
                        ],
                        max_length=255,
                    ),
                ),
                ("available_date", models.DateTimeField(null=True)),
                (
                    "interview_status",
                    models.CharField(
                        choices=[
                            ("In-Process", "In-process"),
                            ("Rejected", "Rejected"),
                            ("Selected", "Selected"),
                            ("Offered", "Offered"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
            ],
            options={
                "verbose_name_plural": "Available Candidates",
                "db_table": "Available Candidates",
            },
        ),
        migrations.CreateModel(
            name="GTIPanelist",
            fields=[
                (
                    "sid",
                    models.CharField(
                        max_length=7, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "lob",
                    models.CharField(
                        choices=[
                            ("CNS", "CNS"),
                            ("EIS", "EIS"),
                            ("EWP", "EWP"),
                            ("PS", "PS"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "prefered_round",
                    models.CharField(
                        choices=[
                            ("SDLC", "SLDC"),
                            ("Architecture", "Architecture"),
                            ("Coding", "Coding"),
                        ],
                        max_length=255,
                    ),
                ),
                ("number_of_interviews_in_a_month", models.PositiveIntegerField()),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Bengaluru", "Bengaluru"),
                            ("Hyderabad", "Hyderabad"),
                            ("Mumbai", "Mumbai"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Available Panelist",
                "db_table": "Available Panelist",
            },
        ),
        migrations.CreateModel(
            name="Interviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Interview_date_time", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "interview_round",
                    models.CharField(
                        choices=[
                            ("SDLC", "SLDC"),
                            ("Architecture", "Architecture"),
                            ("Coding", "Coding"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("In-Process", "In-process"),
                            ("Scheduled", "Scheduled"),
                            ("Cancelled", "Cancelled"),
                            ("Completed", "Completed"),
                            ("On-hold", "On-hold"),
                        ],
                        max_length=22,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Interviews",
                        to="ttt.candidate",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Interviews",
                        to="ttt.gtipanelist",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Scheduled Interviews",
                "db_table": "Scheduled Interviews",
            },
        ),
        migrations.CreateModel(
            name="Requistion",
            fields=[
                (
                    "req_id",
                    models.CharField(
                        max_length=9, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("recruiter", models.CharField(max_length=255)),
                ("hiring_manager", models.CharField(max_length=255)),
                ("start_date", models.DateField(auto_now=True, null=True)),
                ("last_modified_date", models.DateField(null=True)),
                (
                    "lob",
                    models.CharField(
                        choices=[
                            ("CNS", "CNS"),
                            ("EIS", "EIS"),
                            ("EWP", "EWP"),
                            ("PS", "PS"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "req_status",
                    models.CharField(
                        choices=[
                            ("Approved", "Approved"),
                            ("Cancelled", "Cancelled"),
                            ("Completed", "Completed"),
                            ("On-hold", "On-hold"),
                            ("In-progress", "In-progress"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.DeleteModel(
            name="Atadmin",
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.AddField(
            model_name="interviews",
            name="req_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviews",
                to="ttt.requistion",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="req_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate",
                to="ttt.requistion",
            ),
        ),
    ]
