# Generated by Django 4.1.7 on 2023-04-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0004_candidate_gtipanelist_interviews_requistion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requistion',
            name='diversity',
            field=models.CharField(choices=[('Diversity', 'Diversity'), ('Non-Diversity', 'Non-Diversity')], default='Diversity', max_length=20),
        ),
        migrations.AddField(
            model_name='requistion',
            name='grade',
            field=models.CharField(choices=[('601', '601'), ('602', '602'), ('603', '603'), ('604', '604')], default='603', max_length=3),
        ),
        migrations.AddField(
            model_name='requistion',
            name='internal_external',
            field=models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], default='External', max_length=20),
        ),
    ]
