# Generated by Django 4.1.7 on 2023-04-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0005_requistion_diversity_requistion_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requistion',
            name='job_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
